### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by hippogriffic**
@incuna/frontend pls

### CODE REVIEW

**Comment by Minglee01** [comment]
Looks good to merge

Are u updating jquery. If u are please make sure their are no conaole erroes.

**Comment by hippogriffic** [comment]
it is an update, but there are no console errors, and everything still works so it should be ok

**Comment by hippogriffic** [comment]
although I should probably remove it from bower, which I forgot to do

**Comment by Minglee01** [comment]
Goo to merge. Im on mobile so im not gonna do it

**Comment by Minglee01** [comment]
Good idea

**Comment by hippogriffic** [comment]
@Minglee01 happy to merge now?

**Comment by hippogriffic** [comment]
merging as I need it, but let me know if there are comments

**Pull request merged**
